name: 'Ucademy DO Deploy'
description: 'Action for deploying to DO Ucademy apps.'
inputs:
  env:
    description: 'Environment to deploy to'
    required: true
    default: 'prod'
  token:
    description: 'Digital Ocean API token'
    required: true
  tag:
    description: 'Tag to deploy'
    required: true
  services:  
    description: 'Array of modified services'
    required: true
runs:
  using: 'node16'
  main: 'index.js'