name: 'Ucademy DO Deploy'
description: 'Action for deploying to DO Ucademy apps.'
inputs:
  token:
    description: 'Digital Ocean API token'
    required: true
  tag:
    description: 'Tag to deploy'
    required: true
  apps:  
    description: 'Array of modified apps'
    required: true
    default: '['api', 'client']'
outputs:
  result:
    description: 'Result of the deploy'
runs:
  using: 'node16'
  main: 'index.js'