name: 'Ucademy DO Deploy'
description: 'Action for deploying to DO Ucademy apps.'
inputs:
  token:
    description: 'Digital Ocean API token'
    required: true
  tag:
    description: 'Tag to deploy'
    required: true
  apps:  
    description: 'Array of modified apps'
    required: true
runs:
  using: 'node16'
  main: 'index.js'